<?php

return [
	'firstname' => 'Nama depan pemilik polis',
	'lastname' => 'Nama belakang pemilik polis',
	'gender' => 'Jenis kelamin',
	'dob' => 'Tanggal lahir',
	'phoneNumber' => 'Telepon',
	'customerEmail' => 'Email',
	'noKtp' => 'Nomor KTP',
	'firstnameOwner' => 'Nama depan pemilik gadget',
	'lastnameOwner' => 'Nama depan Belakang pemilik gadget',
	'genderOwner' => 'Jenis kelamin',
	'dobOwner' => 'Tanggal lahir',
	'phoneNumberOwner' => 'Telepon',
	'emailOwner' => 'Email',
	'gadgetCategoryId' => 'Perangkat gadget',
	'vendorCode' => 'Vendor',
	'gadgetTypeId' => 'Tipe gadget',
	'lcdColorId' => 'Warna layar LCD',
	'serialNumber' => 'Nomor serial',
	'buyDate' => 'Tanggal pembelian asuransi',
	'premiPerYear' => 'Harga premi asuransi/tahun',
	'locationId' => 'Lokasi',
	'technicianId' => 'Teknisi',
	'cashierId' => 'Kasir',
	'FiledataKTP' => 'Foto KTP',
	'FiledataGadget' => 'Foto layar gadget dengan nomor serial',
	'g-recaptcha-response' => 'Captcha',
	
	'productSparepartId' => 'Sparepart',
	'price' => 'Harga Sparepart',
	'FileImageBeforeRepair' => 'Foto Layar Gadget Dengan Nomor Serial (Sebelum Perbaikan)',
	'FileImageAfterRepair' => 'Foto Layar Gadget Dengan Nomor Serial (Sesudah Perbaikan)',
	'FileInvoice' => 'Invoice',
];